[build]
builder = "docker"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "3000"

[scaling]
minReplicas = 1
maxReplicas = 5
