[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
dependsOn = []
cmds = [
    "apt-get update && apt-get install -y build-essential",
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "python -c 'import app.main; print(\"FastAPI app imports successfully\")'",
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"