[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[scaling]
minReplicas = 1
maxReplicas = 10
autoscaling = true

[networking]
# Enable private networking for internal service communication
privateDomainEnabled = true

[resources]
# Optimized for 120-150 concurrent users
memory = "2Gi"
cpu = "2000m"
