[build]
builder = "nixpacks"

[deploy]
startCommand = "go run main.go"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8005"
