[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
JAVA_OPTS = "-Xmx512m -Xms256m"

[scaling]
minReplicas = 1
maxReplicas = 5
autoscaling = true

[networking]
# Enable private networking for internal service communication
privateDomainEnabled = true

[resources]
# Optimized for code execution microservice
memory = "1Gi"
cpu = "1000m"
