[build]
builder = "nixpacks"

[deploy]
startCommand = "mvn compile exec:java -Dexec.mainClass=Main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8003"
