[build]
builder = "nixpacks"

[deploy]
startCommand = "cargo run --release"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8006"
