[phases.setup]
nixPkgs = ["python310", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["g++ -o main main.cpp"]

[start]
cmd = "python server.py"

[variables]
PORT = "8004"
