[phases.setup]
nixPkgs = ["python310", "gcc", "g++", "pip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["g++ -o main main.cpp"]

[start]
cmd = "/opt/venv/bin/python server.py"

[variables]
PORT = "8004"
PATH = "/opt/venv/bin:$PATH"
